"""add_category_to_participant_clean

Revision ID: a4658f074a36
Revises: 295b2d8d0f58
Create Date: 2024-12-07 09:46:53.694746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4658f074a36'
down_revision = '295b2d8d0f58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'min_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'max_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participant_event', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participant_event', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('participants', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('participants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('participants', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('participants', 'chest_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('participants_chest_number_key', 'participants', type_='unique')
    op.drop_index('ix_participants_chest_number', table_name='participants')
    op.create_index(op.f('ix_participants_chest_number'), 'participants', ['chest_number'], unique=True)
    op.create_foreign_key(None, 'participants', 'categories', ['category_id'], ['id'])
    op.alter_column('results', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('results', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('results', 'judge1_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('results', 'judge2_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('results', 'judge3_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('results', 'total_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('results', 'rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('results', 'total_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('results', 'judge3_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('results', 'judge2_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('results', 'judge1_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('results', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('results', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_index(op.f('ix_participants_chest_number'), table_name='participants')
    op.create_index('ix_participants_chest_number', 'participants', ['chest_number'], unique=False)
    op.create_unique_constraint('participants_chest_number_key', 'participants', ['chest_number'])
    op.alter_column('participants', 'chest_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participants', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participants', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('participants', 'category_id')
    op.alter_column('participant_event', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participant_event', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.alter_column('categories', 'max_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'min_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
